Add support for multiple backends and add HTML backend
Lugrim/seri pull request #12
Opened 2023-04-05 18:58 UTC by hugnata

Add support for multiple backend and add an HTML backend to the compiler.

Add new options for the compiler, namely
```
  -f, --format <FORMAT>      Output format [default: tikz]
  -t, --template <TEMPLATE>  Template to use, if any
  -o, --output <FILE>        Output file. If not present, will output to stdout
̀```

2023-04-05 19:04 UTC, Lugrim commented on README.md
> +## TODO
You can check the HTML > Minimal box, and precise what you would like to add to make it a "not so minimal" HTML output

2023-04-05 19:09 UTC, Lugrim commented on Cargo.toml
Could maybe also deserve a minor version bump I guess, it's satisfying :3

2023-04-05 19:10 UTC, hugnata commented on README.md
> +## TODO
Done !

2023-04-05 19:11 UTC, hugnata commented on Cargo.toml
I love it :tada:

2023-04-05 19:17 UTC, Lugrim commented on src/main.rs
> +use passes::html::{HTMLBackend, HTMLBackendOptions};
To factor things out, you may want to move this in the `use crate` directive (lines 22 and onwards)

2023-04-05 20:03 UTC, Lymkwi requested changes
Overall very good, just finnicky details here and there that could easily be improved :fox_face: :+1:

2023-04-05 20:03 UTC, Lymkwi commented on src/passes/html.rs
> +fn event_to_string(event: &Event) -> String {
Why not directly implement this as an impl of [`ToString`](https://doc.rust-lang.org/std/string/trait.ToString.html) on `Event` ? You would have to also change line 79 to read `str.push(&event.to_string())` rather than `str.push(event_to_string(&event).as_str())`.

2023-04-05 20:03 UTC, Lymkwi commented on src/passes/html.rs
> +    if let Some(path) = &options.template_path {
You could write this entire section as a `map_or_else` instead of an if/let/else:
```
options.template_path.as_ref().map_or_else(|| Ok(include_str!("../../data/template.html").to_string()), |path| match std::fs::read_to_string(path) {
        Ok(template) => Ok(template),
        Err(err) => Err(HTMLBackendCompilationError::CouldNotReadTemplate(err)),
    })
```

2023-04-05 20:03 UTC, Lymkwi commented on src/passes/html.rs
> +    let mut res = String::from(format!("\t\t<td class=\"{class}\" rowspan=\"{duration}\">"));
`format!` already outputs a `String`.

2023-04-05 20:03 UTC, Lymkwi commented on src/passes/html.rs
> +    res.push_str(format!("{}", title).as_str());
You don't need to `format!` and then `.as_str`, because `title` is already a `&str`.

2023-04-05 20:03 UTC, Lymkwi commented on src/passes/html.rs
> +static OPTIONS: Mutex<HTMLBackendOptions> = Mutex::new(HTMLBackendOptions {
Genuinely curious, what is the use of the `Mutex` here? I don't recall there being any parallelism or concurrency in this whole project. I may be mistaken, however.

2023-04-05 20:03 UTC, Lymkwi commented on src/passes/html.rs
> +            str.push_str(format!("\t<tr><th>{}:00</th>", i).as_str());
You can put the `i` in the brackets in the format string :smiley: 
```
"\t<tr><th>{i}:00</th>"
```

EDIT: Same comment for line 82.

2023-04-05 20:03 UTC, Lymkwi commented on src/main.rs
> +            .map_err(|err| CompilerError::CouldNotGenerateHTML(err)),
No need to create a closure here, just pass `CompilerError::CouldNotGenerateHTML` as argument.

2023-04-05 20:03 UTC, Lymkwi commented on src/main.rs
> +            .map_err(|err| CompilerError::CouldNotGenerateHTML(err)),
Oh and same for line 113!

2023-04-05 20:03 UTC, Lymkwi commented on src/main.rs
> +            Some(file_path) => {
You could also use a `map_or_else` here, as suggested by `clippy`, but I agree that it could be a bit overkill. For reference, it would be:
```
        Ok(data) => args.output.map_or_else(|| println!("{data}"), |file_path| {
                 let mut file =
                     File::create(&file_path).expect(format!("Couldnt open {file_path}").as_str());
                 file.write_all(data.as_bytes())
                     .expect("Couldnt write to {file_path}");
             }),
```

2023-04-05 20:03 UTC, Lymkwi commented on src/main.rs
> +                    File::create(&file_path).expect(format!("Couldnt open {file_path}").as_str());
`.expect` is nice for constant strings, but if you are going to format a string, you might want to use an `unwrap_or_else` and voluntarily `panic!` with the formatting in it like `panic!("Couldn't open {file_path}")`.

2023-04-05 20:45 UTC, Docteur-Lalla commented on src/passes/html.rs
> +    if let Some(path) = &options.template_path {
In the present case, wouldn't it be better to go for a `match` construct itself? All these closure make the code complicated, while it could be more straightforward:

```rust
match options.template_path.as_ref() {
    None => Ok(include_str!("../../data/template.html").to_string()),
    Some(path) => std::fs::read_to_string(path).map_err(HTMLBackendCompilationError::from),
}
```

2023-04-05 20:49 UTC, Docteur-Lalla commented on src/passes/html.rs
> +                .filter(|ev| ev.start_date.hour() >= i && ev.start_date.hour() < i + 1)
I don't get this `filter`. You want the hour to be greater or equal to `i` and less than `i + 1`. Given that `hour` returns a `u32` and `i` is an integer itself, isn't it an equality test?

2023-04-05 20:54 UTC, Docteur-Lalla commented on src/passes/html.rs
> +fn get_template() -> Result<String, HTMLBackendCompilationError> {
Given that this function can only fail while reading the template (in `read_to_string`), I would suggest to either return an `std::io::Error` or create a newtype over it. I'm not convince we need a bigger error type, especially since functions that call `get_template` can create a `HTMLBackendCompilationError` from an `std::io::Error` using `from`.

2023-04-05 20:56 UTC, Docteur-Lalla commented on src/passes/html.rs
> +static OPTIONS: Mutex<HTMLBackendOptions> = Mutex::new(HTMLBackendOptions {
I'd also argue that using a static option object make functions non reentrant and as such will make unit-testing even more difficult. We should just use a regular `HTMLBackendOptions` object that we pass as parameter to the functions that need it.

2023-04-05 20:56 UTC, Lymkwi commented on src/passes/html.rs
> +    if let Some(path) = &options.template_path {
Agreed, match makes it easier to read. I'm generally okay with a bunch of closures in my code but I agree that it's not for everyone.

2023-04-05 21:00 UTC, Docteur-Lalla commented on src/event.rs
Please use `cargo fmt` to reformat the code according to *the standard:tm:*

2023-04-05 21:11 UTC, Lugrim commented on src/main.rs
> +    format: String,
Try using directly an enum, see the [ValueEnum](https://docs.rs/clap/latest/clap/trait.ValueEnum.html) trait and [this StackOverflow reply](https://stackoverflow.com/a/73184990)

2023-04-07 12:02 UTC, hugnata commented on src/passes/html.rs
> +fn event_to_string(event: &Event) -> String {
I like the idea ! However, for the data and the passes to stay separated, It would be nice to:

1. Be able to implement [ToString](https://doc.rust-lang.org/std/string/trait.ToString.html) on `Event` in `html.rs` (since only the HTML backend need to convert an Event to an HTML String)
2. Be able to *specialize* the `to_string` function (for example  `to_string<HTML>()` for a HTML representation, and `to_string<TIKZ>()`for a tikz representation), since every backend could need its own `to_string` implementation

Have you got an idea on how we could do this ? (I don't master Rust enough ^^)

2023-04-07 12:12 UTC, Docteur-Lalla commented on src/passes/html.rs
> +fn event_to_string(event: &Event) -> String {
Indeed the to_string here serializes for the HTML backend and not for an "absolute context". Maybe we could have a `ToHTML` trait or something.

2023-04-07 12:22 UTC, Docteur-Lalla commented on src/passes/html.rs
> +fn event_to_string(event: &Event) -> String {
Serde ?

2023-04-07 12:29 UTC, hugnata commented on src/event.rs
This is `cargo fmt` that changed the `src/event.rs` format, I didn't opened the file. Do I need to configure something to get the same formatting as you ? (line size for example)

2023-04-07 13:32 UTC, hugnata reviewed
Thank you very much for your detailed reviews :heart: 
I commited a new version of the code to fix some problem mentioned in the reviews. For some comment, I'm looking for ideas, feel free to propose code or commit directly to the branch.
I'll add another commit to add the ToHTML trait, as proposed by @Docteur-Lalla and @Lugrim

2023-04-07 13:32 UTC, hreymond commented on src/main.rs
> +            .map_err(|err| CompilerError::CouldNotGenerateHTML(err)),
I didn't realised, that's so much simpler oO
I just replaced the awful closure with `CompilerError::from`, that's way better

2023-04-07 13:32 UTC, hugnata commented on src/passes/html.rs
> +static OPTIONS: Mutex<HTMLBackendOptions> = Mutex::new(HTMLBackendOptions {
I wanted to be able to configure the backend pass without modifiyng the interface provided in `passes.rs`, and more importantly the signature of `apply`,  used in `chain_pass`: `fn apply(_: T) -> Result<Self::Residual, Self::Error>;`.

The only solution I found for now is to have a static variable that contains the parameters of the pass, that can be used afterwards by `apply`. However, having a static variable means having potential data races, which rust compiler does not like. Thus, i protected the variable with a mutex, which is really ugly I agree.

If you have any idea on how to handle parameters without changing `apply`signature, I'm in ! Otherwise we could think of changing the interface, but it's another whole story and we should create a new issue/branch/PR

2023-04-07 13:32 UTC, hugnata commented on src/passes/html.rs
> +    if let Some(path) = &options.template_path {
I agree, this is a bit of a mess, I've modified this part of the code, it should be better !

2023-04-07 13:32 UTC, hugnata commented on src/main.rs
> +                    File::create(&file_path).expect(format!("Couldnt open {file_path}").as_str());
Good idea ! Done :wink:

2023-04-07 13:32 UTC, hugnata commented on src/main.rs
> +    format: String,
Thanks for the link ! I didn't know it was possible

2023-04-07 13:35 UTC, hugnata commented on src/passes/html.rs
> +                .filter(|ev| ev.start_date.hour() >= i && ev.start_date.hour() < i + 1)
For now it's only handling event that start at a round hour. In the future, I hope to add support for half-hour and minute precision.

2023-04-07 13:45 UTC, Lymkwi commented on src/passes/html.rs
> +static OPTIONS: Mutex<HTMLBackendOptions> = Mutex::new(HTMLBackendOptions {
I think it should not be too hard to spin up another method in the Trait that can be invoked with an argument of a type associated to the trait (with default to `()` if not given by the `impl`). I could do a quick demo and PR for it.

2023-04-07 13:48 UTC, Lymkwi commented on src/passes/html.rs
> +fn event_to_string(event: &Event) -> String {
Serde would also be sort of an "absolute context" converter I think, but the middle ground of a `ToHTML` trait is fair enough, I think it solves the need to convert in this module specifically without implying a universal format for `Event`.

2023-04-07 13:52 UTC, Lymkwi reviewed
I think I would like to see the `ToHTML` trait added before merging, but otherwise, looks good, and all the little details have been fixed.

2023-04-07 14:34 UTC, Lymkwi commented on src/passes/html.rs
> +static OPTIONS: Mutex<HTMLBackendOptions> = Mutex::new(HTMLBackendOptions {
Quick and dirty proposal available at 12659d836bf599654b0eeeafba0fc0271981cb1b

2023-04-07 14:39 UTC, hugnata commented on src/passes/html.rs
> +fn event_to_string(event: &Event) -> String {
Done with a ToHTML trait :wink:

2023-04-07 14:42 UTC, Lymkwi approved these changes

2023-04-07 15:58 UTC, hugnata commented on src/main.rs
> +/// Write the output to a file or to stdout
I moved the "writing to the output file" logic out of the mess that was l.140.

After a bit of refactoring, I'm not sure it is necessary to have a separated function. Any thoughs on this ?

2023-04-07 16:07 UTC, hugnata reviewed
I added the contextual pass management proposed by @Lymkwi, so now the parameters are given to the HTML backend with ` .chain_pass_with::<HTMLBackend, HTMLBackendOptions>(options)`
I used clippy to fix few things, and removed clippy warnings for other parts.

2023-04-07 16:07 UTC, hreymond commented on src/main.rs
> +
I moved the "writing to the output file" logic out of the mess that was l.140.

After a bit of refactoring, I'm not sure it is necessary to have a separated function. Any thoughs on this ?

2023-04-07 16:07 UTC, hugnata commented on src/passes/html.rs
> +
I removed Clippy warnings about using `template_path.map_or_else()` instead of the match structure, since I find it easier to read

2023-04-07 16:07 UTC, hugnata commented on src/passes.rs
>  /// A trait defining compilation passes
I added documentation for the `CompilingPass` trait + a simple example.
I don't know the standard for documenting Rust, and I'm afraid to say wrong things.
Can you check it out ?

2023-04-07 16:09 UTC, hugnata commented
Is there a way to change the status of the PR to "change not approved yet ?" (since the code changed a lot since @Lymkwi approved my changes).

2023-04-07 16:27 UTC, Lymkwi commented
> Is there a way to change the status of the PR to "change not approved yet ?" (since the code changed a lot since @Lymkwi approved my changes).

Someone can request another review from me on the Desktop UI.

2023-04-07 18:21 UTC, Lymkwi commented on src/main.rs
> +
We're at such a level of overengineering, I don't see how factoring out logic like that could hurt.

2023-04-07 18:25 UTC, Lymkwi commented on src/passes/html.rs
> +
Agreed. It saves in performance to not do it that way but who cares.

2023-04-07 18:26 UTC, Lymkwi approved these changes

2023-04-07 19:16 UTC, hugnata commented
You can merge when you want 😉

2023-04-09 22:05 UTC, merged